configuration:
  - Debug

environment:
  matrix:
  - TOOLCHAIN: Msvc 2017 x86
    GENERATOR: Visual Studio 15 2017

  - TOOLCHAIN: Msvc 2017 x64
    GENERATOR: Visual Studio 15 2017 Win64

  - TOOLCHAIN: Msvc 2017 x64/Ninja
    GENERATOR: Ninja
    VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat

image:
  - Visual Studio 2017

install:
  - cmd: pip install ninja cmake --disable-pip-version-check

before_build:
  - cmd: if defined VCVARS call "%VCVARS%"
  - ps: mkdir build
  - ps: cd build
  - cmd: cmake .. -G"%GENERATOR%"

build_script:
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest --output-on-failure -C %CONFIGURATION%
